Feature/e commerce
rychcicki/design-patterns pull request #1
Opened 2023-09-03 14:17 UTC by rychcicki

2023-09-03 17:25 UTC, Y0ucandev requested changes

2023-09-03 17:25 UTC, Y0ucandev commented on e-commerce/.idea/vcs.xml
jakos zle ci ten gitignore dziala bo pelno syfu chcesz na repo wepchac

2023-09-03 17:25 UTC, Y0ucandev commented on e-commerce/pom.xml
> +
zbedna pusta linia

2023-09-03 17:25 UTC, Y0ucandev commented on e-commerce/src/main/java/org/example/Payment.java
> +    <T> T chooseMethodOfPayment(T paymentMetod) {
Po co to jest metoda generyczna ? Bardzo to komplikuje kod 
To samo bys osiagnal majac sam interfejs. W ogole po co to jest generykiem skoro od tego typu nic dalej nie zalezy i metody sa voidowe i tak ?

2023-09-03 20:08 UTC, rychcicki commented on e-commerce/.idea/vcs.xml
Bo może na samym początku trzeba z maina wrzucić gitignore na githuba i dopiero wtedy Fork nie będzie widzieć tych plików??

2023-09-03 20:09 UTC, rychcicki commented on e-commerce/pom.xml
> +
Nie widzę tego pliku - odrzuć zmiany, czy coś.

2023-09-03 20:10 UTC, rychcicki commented on e-commerce/src/main/java/org/example/Payment.java
> +    <T> T chooseMethodOfPayment(T paymentMetod) {
Nie widzę żadnych plików z klasami Javy, bo są wykomitowane - odrzuć zmiany, czy coś.

2023-09-03 20:30 UTC, Y0ucandev commented on e-commerce/.idea/vcs.xml
najpierw musisz wypushowac gitingnore
i dopiero potem bd dzialac

2023-09-03 20:31 UTC, Y0ucandev commented on e-commerce/pom.xml
> +
Jak odrzuce to wyrzuce Twoj caly kod wiec sie zastanow czy tego wlasnie chcesz

2023-09-03 20:31 UTC, Y0ucandev commented on e-commerce/src/main/java/org/example/Payment.java
> +    <T> T chooseMethodOfPayment(T paymentMetod) {
nie rozumiem

2023-09-04 22:18 UTC, rychcicki commented on e-commerce/src/main/java/org/example/Payment.java
> +    <T> T chooseMethodOfPayment(T paymentMetod) {
Chodzi o to, że jak robię w Forku nowy branch i dopiero później tworzę klasy, to po push-u nie widzę ich w Intellij-u. Ten problem już miałem kilka razy, ale najczęściej radziłem sobie scalając to w mainie. Może uda Ci się rozwiązać ten problem w środę.
Co do metody chooseMethodOfPayment() , to jest ona po to, żeby przyjąć metodę płatności na zrobionej 1 instancji klasy Payment. Tak, wiem, że można też dowolną klasę wstawić w tej metodzie, ale w zwróconej instancji dowolnej klasy nie można implementować metody z interfejsu. 
Z drugiej strony mając sam interfejs lub klasę abstrakcyjną nie będziemy mogli zrobić ich instancji - co najwyżej instancję klasy anonimowej, ale tego chciałem uniknąć.
Czyli tak -  mamy serwis z płatnościami: 1 instancja Payment i wybór płatności na tej instancji - tak jak wywołałem w klasie Main.
Przynajmniej tak to sobie wymyśliłem i zmieściłem się w 2 h.

2023-09-05 10:12 UTC, Y0ucandev commented on e-commerce/src/main/java/org/example/Payment.java
> +    <T> T chooseMethodOfPayment(T paymentMetod) {
Niby dlaczego ? 
Na zajęciach Ci pokaże w minute że wyrzucając generyka z interfejsu nie musze nawet dotykać kodu żeby działał. 
Po drugie zrobienie tego : 
`  payment.chooseMethodOfPayment(new Bitcoin()).pay(new BigDecimal("12.54"));
 <T> T chooseMethodOfPayment(T paymentMetod) {
        return paymentMetod;
    }`
    Jest totalnym bezsensem bo zwracasz samego siebie czyli generyka ale po co ? 
    Przypomnij mi abym przerobił na zajęciach Twój kod bo tutaj mocno odpłynąłeś z koncepcjami i wyciągasz armate na mysz nie wiadomo po co.
Jakies generyki metody generyczne interfejsy generyczne zwracanie samego siebie. 
A ja to moge obgonic jednym interfejsem bez praktycznie tykania Twojego kodu

2025-02-26 23:25 UTC, merged