Feature/strategy
rychcicki/design-patterns pull request #2
Opened 2023-09-12 23:06 UTC by rychcicki

2023-09-12 23:07 UTC, rychcicki commented
Strategia to na razie tylko draft.

2023-09-25 14:11 UTC, Y0ucandev requested changes

2023-09-25 14:11 UTC, Y0ucandev commented on e-commerce/src/main/java/org/example/strategy/Bridge.java
> +    @Builder
czemu uzywasz buildera tu a nie nad klasa ? :D

2023-09-25 14:11 UTC, Y0ucandev commented on e-commerce/src/main/java/org/example/strategy/BridgeBuilder.java
> +        for (Object bridge : engineeringObject) {
nie ma lepszej drogi do zrobienia tego ? tylko forEach po kazdym obiekcie. 
Tez fakt castowania tego z Obiektu mi sie jakos super nie podoba. Zamiast ? lepiej moze zrobic T

2023-09-25 14:11 UTC, Y0ucandev commented on e-commerce/src/main/java/org/example/strategy/CulvertBuilder.java
> +    public static List<Culvert> buildNewCulvertFromObject(List<?> engineeringObject) {
tak samo jak wyzej

2023-09-25 14:11 UTC, Y0ucandev commented on e-commerce/src/main/java/org/example/strategy/HeightCalculateService.java
> +    private final HeightCalculateStrategy strategy;   //interface
zbedny komentarz

2023-09-25 14:11 UTC, Y0ucandev commented on e-commerce/src/main/java/org/example/strategy/HeightCalculateService.java
> +    }   //Można Lombokiem @AllArgsConstructor
komentarz do usuniecia. 
A jezeli mozna lombokiem to czemu nie zrobic tego lombokiem ?

2023-09-25 14:11 UTC, Y0ucandev commented on e-commerce/src/main/java/org/example/strategy/RailwayBridgeStrategy.java
> +        for (Bridge bridge : bridges) {
sprawdzales czy uda sie zamienic na streama ? :D

2023-09-25 14:11 UTC, Y0ucandev commented on e-commerce/src/main/java/org/example/strategy/RailwayBridgeStrategy.java
> +        System.out.println("Calculate railway's bridge height finished.");
uzywaj loggera. Na tym etapie zaawansowania sout to zenada ;D

2023-09-25 22:30 UTC, rychcicki commented on e-commerce/src/main/java/org/example/strategy/Bridge.java
> +    @Builder
Bo ucząc się ostatnio @Buildera z Lomboka dowiedziałem się, że jest taka opcja:-) W tym konkretnie przypadku wymuszam stworzenie konstruktora tylko z takimi polami. Chodzi o to, żeby tworząc instancję obiektu nie było możliwości ustawiania pola height - jest ustawiane poprzez obliczenia.

2023-09-25 22:35 UTC, rychcicki commented on e-commerce/src/main/java/org/example/strategy/HeightCalculateService.java
> +    }   //Można Lombokiem @AllArgsConstructor
Wszystkie komentarze w tej klasie są/były tylko dla mnie - łatwiej mi to jest zrozumieć i zapamiętać.

2023-09-26 18:49 UTC, rychcicki commented on e-commerce/src/main/java/org/example/strategy/BridgeBuilder.java
> +        for (Object bridge : engineeringObject) {
Nie bardzo wiem jak zrobić, żeby castować Object na Culvert i Bridge i dodać je do odrębnych list do. Wymyśliłem coś, ale trochę to naciągane (raw List).

2023-09-26 19:09 UTC, Y0ucandev requested changes

2023-09-26 19:09 UTC, Y0ucandev commented on e-commerce/src/main/java/org/example/builder/CreditCard.java
> +// Nad konstruktorem tworzy konstruktor zawierający tylko te pola
to bez sensu troche taki builder w wiekszosci przypadkow jak ograniczasz liczbe pol ktore mozesz setupowac. Po to wlasnie builder jest zeby tego nie robic

2023-09-26 19:09 UTC, Y0ucandev commented on e-commerce/src/main/java/org/example/builder/Person.java
> +    public static class ObjBuilder {
dobra strategia jest nazywac builder NazwaKlasyBuilder

2023-09-26 19:09 UTC, Y0ucandev commented on e-commerce/src/main/java/org/example/builder/Student.java
> +    //    @Builder
do wyrzucenia te komentarze raczej

2023-09-26 19:09 UTC, Y0ucandev commented on e-commerce/src/main/java/org/example/builder/Student.java
> +         * Po co ten toString() jak i tak nie odnosi się do klasy, której obiekt zwraca??
Pytasz mnie ? To Twoj kod

2023-09-26 19:09 UTC, Y0ucandev commented on e-commerce/src/main/java/org/example/builder/Wallet.java
> +    private final Set<String> listOfCurrencies;   //niemodyfikowalna kolekcja
Od kiedy?

2023-09-26 19:09 UTC, Y0ucandev commented on e-commerce/src/main/java/org/example/factoryMethod/Main.java
> + * Zrób repo sobie design-patterns na gicie i dodaj mnie do niego i zrób PR. Ja przeprowadzę Code review.
do wywalenia

2023-09-26 19:09 UTC, Y0ucandev commented on e-commerce/src/main/java/org/example/strategy/Bridge.java
> +    @Builder
ok

2023-09-26 21:28 UTC, rychcicki commented on e-commerce/src/main/java/org/example/builder/CreditCard.java
> +// Nad konstruktorem tworzy konstruktor zawierający tylko te pola
Tak jest w przykładach użycia. Chodziło mi o zapoznanie się z wieloma przypadkami użycia @Builder.

2023-09-26 21:31 UTC, rychcicki commented on e-commerce/src/main/java/org/example/builder/Student.java
> +    //    @Builder
Niech zostaną. Łatwiej jest mi odszukać i zapamiętać poszczególne kroki.

2023-09-26 21:33 UTC, rychcicki commented on e-commerce/src/main/java/org/example/builder/Student.java
> +         * Po co ten toString() jak i tak nie odnosi się do klasy, której obiekt zwraca??
Wszędzie w przykładach tak jest, ale to i tak nie działa, bo wywołanie odnosi się do innej klasy.

2023-09-26 21:50 UTC, rychcicki commented on e-commerce/src/main/java/org/example/builder/Wallet.java
> +    private final Set<String> listOfCurrencies;   //niemodyfikowalna kolekcja
To było na szybko, a później mówiłeś, że nie muszę robić implementacji z @Singularem.
Oczywiście, że jest set jest modyfikowalny. Builder przy takim polu wielokrotnie dodaje obiekty do kolekcji.
Final tylko ogranicza możliwość zmiany referencji do obiektu (nie można przypisać innego seta).

2023-09-26 21:51 UTC, rychcicki commented on e-commerce/src/main/java/org/example/builder/Student.java
> +    //    @Builder
W pakiecie .builder komentarze pozostaną dla mnie:-)

2025-02-26 23:32 UTC, merged